### PR TITLE
Fixes #98 and #77

### LINKED ISSUE #77: Profile Page Crashes If Not Logged In
```
                //TODO Profile Page Crashes If Not Logged In
```

https://github.com/ntseng/w12-groupproject/blob/e673131e05a1ecb420b1941a011f33c01d4315c1/views/profile-page.pug#L12

### LINKED ISSUE #98: Upvotes can be done if not logged in (home page)

### PR DESCRIPTION
**Pull request by ntseng**
- upvotes can be done while not logged in
- profile page crashes if viewed while not logged in

### CODE REVIEW

File: routes/profiles.js [hunk 1]
```diff
@@ -48,10 +48,8 @@ router.get(
 
     let extensions = profileUser.Extensions
     let comments = profileUser.Comments
-    // console.log(profileUser.Extensions[0].name)
-    // console.log(profileUser.Comments[0].content)
 
-    res.render('profile-page', { title: "Profile Page", profileUser, req, extensions, comments, csrfToken: req.csrfToken() })
+    res.render('profile-page', { title: "Profile Page", profileUser, req, extensions, comments, csrfToken: req.csrfToken(), authenticated: !!res?.locals.authenticated })
```
Comment (Noslepr) [inline routes/profiles.js:52]: I'm not sure how to read this line regarding the authenticated. I am assuming it returns authenticated as a boolean that is then read in the profile-page.pug. I guess I just don't know that syntax.

**Review by Noslepr — APPROVED** [review]

File: routes/profiles.js (hunk 1 above)
Comment (ntseng) [reply routes/profiles.js:52]: `res?.locals.authenticated` returns undefined instead of crashing if `res.locals` is undefined. `!!` double negates the truthyness or falseyness of a value given; essentially giving the literals `true` or `false` based on if the value exists.

**Review by Sheeptoaster — APPROVED** [review]
